name: Python Code Quality Testing

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ${{ vars.RUNNER }}

jobs:
  code-quality:
    name: Check Python Code Quality
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Check code formatting with isort
        working-directory: ${{ vars.APP_DIR }}
        run: isort . --check-only

      - name: Check code formatting with black
        working-directory: ${{ vars.APP_DIR }}
        run: black --check .

      - name: Check code formatting with Flake8
        working-directory: ${{ vars.APP_DIR }}
        run: flake8 .
